import { SidebarLink, Printers, Parts, Users } from "@/types";

export const sidebarLinks: SidebarLink[] = [
  {
    imgURL: "/images/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/assets/icons/storage.svg",
    route: "/storage",
    label: "Storage",
  },
  {
    imgURL: "/images/icons/printer.svg",
    route: "/printers",
    label: "Printers",
  },
  {
    imgURL: "/images/icons/users.svg",
    route: "/users",
    label: "Users",
  },
  {
    imgURL: "/assets/icons/parts.svg",
    route: "/parts",
    label: "Parts",
  },
  {
    imgURL: "/assets/icons/gear.svg",
    route: "/settings",
    label: "Settings",
  },
  // {
  //   imgURL: "/images/icons/suitcase.svg",
  //   route: "/jobs",
  //   label: "Find Jobs",
  // },
  // {
  //   imgURL: "/images/icons/tag.svg",
  //   route: "/tags",
  //   label: "Tags",
  // },
  // {
  //   imgURL: "/assets/icons/user.svg",
  //   route: "/profile",
  //   label: "Profile",
  // },
  // {
  //   imgURL: "/assets/icons/question.svg",
  //   route: "/ask-question",
  //   label: "Ask a question",
  // },
];

export const printerParts: Parts[] = [
  {
    model: "1300",
    leftSide: 5,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 5,
    topMax: 5,
    screens: 10,
    screensMax: 10,
    front: 5,
    frontMax: 5,
    rearDoors: 5,
    rearDoorsMax: 5,
    trays: 5,
    traysMax: 5,
    fuser: 5,
    fuserMax: 5,
    rolls: 10,
    rollsMax: 10,
  },
  {
    model: "1320",
    leftSide: 3,
    leftSideMax: 5,
    rightSide: 4,
    rightSideMax: 5,
    top: 4,
    topMax: 5,
    screens: 7,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 3,
    traysMax: 5,
    fuser: 4,
    fuserMax: 5,
    rolls: 4,
    rollsMax: 10,
  },
  {
    model: "1515",
    leftSide: 5,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 4,
    topMax: 5,
    screens: 7,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 3,
    traysMax: 5,
    fuser: 5,
    fuserMax: 5,
    rolls: 10,
    rollsMax: 10,
  },
  {
    model: "148",
    leftSide: 2,
    leftSideMax: 5,
    rightSide: 2,
    rightSideMax: 5,
    top: 2,
    topMax: 5,
    screens: 2,
    screensMax: 10,
    front: 3,
    frontMax: 5,
    rearDoors: 1,
    rearDoorsMax: 5,
    trays: 3,
    traysMax: 5,
    fuser: 3,
    fuserMax: 5,
    rolls: 1,
    rollsMax: 10,
  },
  {
    model: "130",
    leftSide: 4,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 2,
    topMax: 5,
    screens: 7,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 5,
    traysMax: 5,
    fuser: 5,
    fuserMax: 5,
    rolls: 8,
    rollsMax: 10,
  },
  {
    model: "252",
    leftSide: 2,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 2,
    topMax: 5,
    screens: 7,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 3,
    traysMax: 5,
    fuser: 5,
    fuserMax: 4,
    rolls: 6,
    rollsMax: 10,
  },
  {
    model: "255",
    leftSide: 5,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 2,
    topMax: 5,
    screens: 3,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 3,
    traysMax: 5,
    fuser: 5,
    fuserMax: 5,
    rolls: 10,
    rollsMax: 10,
  },
  {
    model: "277",
    leftSide: 3,
    leftSideMax: 5,
    rightSide: 2,
    rightSideMax: 5,
    top: 2,
    topMax: 5,
    screens: 7,
    screensMax: 10,
    front: 4,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 5,
    trays: 4,
    traysMax: 5,
    fuser: 5,
    fuserMax: 5,
    rolls: 1,
    rollsMax: 10,
  },
  {
    model: "452",
    leftSide: 3,
    leftSideMax: 5,
    rightSide: 5,
    rightSideMax: 5,
    top: 4,
    topMax: 5,
    screens: 2,
    screensMax: 10,
    front: 5,
    frontMax: 5,
    rearDoors: 2,
    rearDoorsMax: 4,
    trays: 3,
    traysMax: 5,
    fuser: 2,
    fuserMax: 5,
    rolls: 10,
    rollsMax: 10,
  },
];
